server:
  port: 8083
    
# Configure routes for the order service.
spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/orders/**